baseurl: "https://how.wtf/"
relativeURLs: true
languageCode: en-us
title: how.wtf
theme: "hugo-tania"
paginate: 8
googleAnalytics: G-0W6GZ3EH9R
uglyurls: true

params:
  titleLogo: images/08WeMC.png
  images:
  - images/8yRnin.png
  enableFootnotes: true
  siteName: how.wtf
  siteDesc: A blog providing how-to articles about development languages and the cloud.
  author: Thomas Taylor
  maxCategoryToShow: 10
  socialOptions:
    email: thomas@how.wtf
    github: https://github.com/thomasnotfound/how.wtf
    twitter: https://twitter.com/thomasnotvalid
  comments:
    enabled: true
    provider: giscus
    giscus:
      repo: thomasnotfound/how.wtf
      id: MDEwOlJlcG9zaXRvcnkzNTg5NzAyOTY=
      category:
        name: Blog Posts
        id: DIC_kwDOFWVzuM4B-NTf

permalinks:
  post: :title

menu:
  header:
  - name: About
    url: "/about.html"
  - name: Articles
    url: "/articles.html"
  footer:
  - name: About
    url: "/about.html"
  - name: Articles
    url: "/articles.html"
  - name: GitHub
    url: "https://github.com/thomasnotfound/how.wtf"
  - name: RSS
    url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

outputs:
  home: ["HTML", "RSS", "JSON"]
